export const LOCALSTORAGE_CONSTANTS = {
    CURRENT_PAGE: "CURRENT_PAGE",
    REGISTER_CONFIRMING_USER: "REGISTER_CONFIRMING_USER",
    UNSEEN_NOTIFICATION_LIST: "UNSEEN_NOTIFICATION_LIST",
    USER_SEEN_NOTIFICATION: "USER_SEEN_NOTIFICATION",
}