name: CI-build-and-push-image-for-dotnetapp

# Controls when the action will run.
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      - '**/.dockerignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
      - '**/.dockerignore'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Thêm bước cài đặt Node.js và npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Chọn phiên bản Node.js bạn muốn sử dụng, thay vì '14'

      # Bước npm install
      - name: Install dependencies
        run: npm i
        working-directory: ./  # Thay đổi thư mục nếu cần

      # Bước npm run dev
      - name: Run npm dev
        run: npm run dev
        working-directory: ./  # Thay đổi thư mục nếu cần

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Đường dẫn tới Dockerfile của bạn
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/management:latest, ${{ secrets.DOCKERHUB_USERNAME }}/management:${{ github.run_number }}
